/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JokesRouteImport } from './routes/jokes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SetsIndexRouteImport } from './routes/sets.index'
import { Route as JokesIndexRouteImport } from './routes/jokes.index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as SetsIdRouteImport } from './routes/sets.$id'
import { Route as JokesIdRouteImport } from './routes/jokes.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesRoute = JokesRouteImport.update({
  id: '/jokes',
  path: '/jokes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SetsIndexRoute = SetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetsRoute,
} as any)
const JokesIndexRoute = JokesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JokesRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)
const SetsIdRoute = SetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SetsRoute,
} as any)
const JokesIdRoute = JokesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JokesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jokes': typeof JokesRouteWithChildren
  '/login': typeof LoginRoute
  '/sets': typeof SetsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/jokes/$id': typeof JokesIdRoute
  '/sets/$id': typeof SetsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/jokes/': typeof JokesIndexRoute
  '/sets/': typeof SetsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jokes/$id': typeof JokesIdRoute
  '/sets/$id': typeof SetsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/jokes': typeof JokesIndexRoute
  '/sets': typeof SetsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jokes': typeof JokesRouteWithChildren
  '/login': typeof LoginRoute
  '/sets': typeof SetsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/jokes/$id': typeof JokesIdRoute
  '/sets/$id': typeof SetsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/jokes/': typeof JokesIndexRoute
  '/sets/': typeof SetsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jokes'
    | '/login'
    | '/sets'
    | '/users'
    | '/jokes/$id'
    | '/sets/$id'
    | '/users/$id'
    | '/jokes/'
    | '/sets/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/jokes/$id'
    | '/sets/$id'
    | '/users/$id'
    | '/jokes'
    | '/sets'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/jokes'
    | '/login'
    | '/sets'
    | '/users'
    | '/jokes/$id'
    | '/sets/$id'
    | '/users/$id'
    | '/jokes/'
    | '/sets/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JokesRoute: typeof JokesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetsRoute: typeof SetsRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes': {
      id: '/jokes'
      path: '/jokes'
      fullPath: '/jokes'
      preLoaderRoute: typeof JokesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/sets/': {
      id: '/sets/'
      path: '/'
      fullPath: '/sets/'
      preLoaderRoute: typeof SetsIndexRouteImport
      parentRoute: typeof SetsRoute
    }
    '/jokes/': {
      id: '/jokes/'
      path: '/'
      fullPath: '/jokes/'
      preLoaderRoute: typeof JokesIndexRouteImport
      parentRoute: typeof JokesRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/sets/$id': {
      id: '/sets/$id'
      path: '/$id'
      fullPath: '/sets/$id'
      preLoaderRoute: typeof SetsIdRouteImport
      parentRoute: typeof SetsRoute
    }
    '/jokes/$id': {
      id: '/jokes/$id'
      path: '/$id'
      fullPath: '/jokes/$id'
      preLoaderRoute: typeof JokesIdRouteImport
      parentRoute: typeof JokesRoute
    }
  }
}

interface JokesRouteChildren {
  JokesIdRoute: typeof JokesIdRoute
  JokesIndexRoute: typeof JokesIndexRoute
}

const JokesRouteChildren: JokesRouteChildren = {
  JokesIdRoute: JokesIdRoute,
  JokesIndexRoute: JokesIndexRoute,
}

const JokesRouteWithChildren = JokesRoute._addFileChildren(JokesRouteChildren)

interface SetsRouteChildren {
  SetsIdRoute: typeof SetsIdRoute
  SetsIndexRoute: typeof SetsIndexRoute
}

const SetsRouteChildren: SetsRouteChildren = {
  SetsIdRoute: SetsIdRoute,
  SetsIndexRoute: SetsIndexRoute,
}

const SetsRouteWithChildren = SetsRoute._addFileChildren(SetsRouteChildren)

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JokesRoute: JokesRouteWithChildren,
  LoginRoute: LoginRoute,
  SetsRoute: SetsRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
