/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SetlistsRouteImport } from './routes/setlists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BitsRouteImport } from './routes/bits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SetlistsIndexRouteImport } from './routes/setlists.index'
import { Route as BitsIndexRouteImport } from './routes/bits.index'
import { Route as UsersIdRouteImport } from './routes/users.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsRoute = SetlistsRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BitsRoute = BitsRouteImport.update({
  id: '/bits',
  path: '/bits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SetlistsIndexRoute = SetlistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetlistsRoute,
} as any)
const BitsIndexRoute = BitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BitsRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bits': typeof BitsRouteWithChildren
  '/login': typeof LoginRoute
  '/setlists': typeof SetlistsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/users/$id': typeof UsersIdRoute
  '/bits/': typeof BitsIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/users/$id': typeof UsersIdRoute
  '/bits': typeof BitsIndexRoute
  '/setlists': typeof SetlistsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bits': typeof BitsRouteWithChildren
  '/login': typeof LoginRoute
  '/setlists': typeof SetlistsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/users/$id': typeof UsersIdRoute
  '/bits/': typeof BitsIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bits'
    | '/login'
    | '/setlists'
    | '/users'
    | '/verify-email'
    | '/users/$id'
    | '/bits/'
    | '/setlists/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify-email'
    | '/users/$id'
    | '/bits'
    | '/setlists'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/bits'
    | '/login'
    | '/setlists'
    | '/users'
    | '/verify-email'
    | '/users/$id'
    | '/bits/'
    | '/setlists/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitsRoute: typeof BitsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetlistsRoute: typeof SetlistsRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists': {
      id: '/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof SetlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bits': {
      id: '/bits'
      path: '/bits'
      fullPath: '/bits'
      preLoaderRoute: typeof BitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/setlists/': {
      id: '/setlists/'
      path: '/'
      fullPath: '/setlists/'
      preLoaderRoute: typeof SetlistsIndexRouteImport
      parentRoute: typeof SetlistsRoute
    }
    '/bits/': {
      id: '/bits/'
      path: '/'
      fullPath: '/bits/'
      preLoaderRoute: typeof BitsIndexRouteImport
      parentRoute: typeof BitsRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
  }
}

interface BitsRouteChildren {
  BitsIndexRoute: typeof BitsIndexRoute
}

const BitsRouteChildren: BitsRouteChildren = {
  BitsIndexRoute: BitsIndexRoute,
}

const BitsRouteWithChildren = BitsRoute._addFileChildren(BitsRouteChildren)

interface SetlistsRouteChildren {
  SetlistsIndexRoute: typeof SetlistsIndexRoute
}

const SetlistsRouteChildren: SetlistsRouteChildren = {
  SetlistsIndexRoute: SetlistsIndexRoute,
}

const SetlistsRouteWithChildren = SetlistsRoute._addFileChildren(
  SetlistsRouteChildren,
)

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitsRoute: BitsRouteWithChildren,
  LoginRoute: LoginRoute,
  SetlistsRoute: SetlistsRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
