/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedSetlistsRouteImport } from './routes/_authed/setlists'
import { Route as AuthedBitsRouteImport } from './routes/_authed/bits'
import { Route as AuthedUsersIndexRouteImport } from './routes/_authed/users.index'
import { Route as AuthedSetlistsIndexRouteImport } from './routes/_authed/setlists.index'
import { Route as AuthedBitsIndexRouteImport } from './routes/_authed/bits.index'
import { Route as AuthedUsersIdRouteImport } from './routes/_authed/users.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSetlistsRoute = AuthedSetlistsRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBitsRoute = AuthedBitsRouteImport.update({
  id: '/bits',
  path: '/bits',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIndexRoute = AuthedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedUsersRoute,
} as any)
const AuthedSetlistsIndexRoute = AuthedSetlistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSetlistsRoute,
} as any)
const AuthedBitsIndexRoute = AuthedBitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedBitsRoute,
} as any)
const AuthedUsersIdRoute = AuthedUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/bits': typeof AuthedBitsRouteWithChildren
  '/setlists': typeof AuthedSetlistsRouteWithChildren
  '/users': typeof AuthedUsersRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/users/$id': typeof AuthedUsersIdRoute
  '/bits/': typeof AuthedBitsIndexRoute
  '/setlists/': typeof AuthedSetlistsIndexRoute
  '/users/': typeof AuthedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof PublicLoginRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/users/$id': typeof AuthedUsersIdRoute
  '/bits': typeof AuthedBitsIndexRoute
  '/setlists': typeof AuthedSetlistsIndexRoute
  '/users': typeof AuthedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/bits': typeof AuthedBitsRouteWithChildren
  '/_authed/setlists': typeof AuthedSetlistsRouteWithChildren
  '/_authed/users': typeof AuthedUsersRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/users/$id': typeof AuthedUsersIdRoute
  '/_authed/bits/': typeof AuthedBitsIndexRoute
  '/_authed/setlists/': typeof AuthedSetlistsIndexRoute
  '/_authed/users/': typeof AuthedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bits'
    | '/setlists'
    | '/users'
    | '/login'
    | '/verify-email'
    | '/users/$id'
    | '/bits/'
    | '/setlists/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify-email'
    | '/users/$id'
    | '/bits'
    | '/setlists'
    | '/users'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/bits'
    | '/_authed/setlists'
    | '/_authed/users'
    | '/_public/login'
    | '/_public/verify-email'
    | '/_authed/'
    | '/_authed/users/$id'
    | '/_authed/bits/'
    | '/_authed/setlists/'
    | '/_authed/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/setlists': {
      id: '/_authed/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof AuthedSetlistsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bits': {
      id: '/_authed/bits'
      path: '/bits'
      fullPath: '/bits'
      preLoaderRoute: typeof AuthedBitsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/': {
      id: '/_authed/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedUsersIndexRouteImport
      parentRoute: typeof AuthedUsersRoute
    }
    '/_authed/setlists/': {
      id: '/_authed/setlists/'
      path: '/'
      fullPath: '/setlists/'
      preLoaderRoute: typeof AuthedSetlistsIndexRouteImport
      parentRoute: typeof AuthedSetlistsRoute
    }
    '/_authed/bits/': {
      id: '/_authed/bits/'
      path: '/'
      fullPath: '/bits/'
      preLoaderRoute: typeof AuthedBitsIndexRouteImport
      parentRoute: typeof AuthedBitsRoute
    }
    '/_authed/users/$id': {
      id: '/_authed/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthedUsersIdRouteImport
      parentRoute: typeof AuthedUsersRoute
    }
  }
}

interface AuthedBitsRouteChildren {
  AuthedBitsIndexRoute: typeof AuthedBitsIndexRoute
}

const AuthedBitsRouteChildren: AuthedBitsRouteChildren = {
  AuthedBitsIndexRoute: AuthedBitsIndexRoute,
}

const AuthedBitsRouteWithChildren = AuthedBitsRoute._addFileChildren(
  AuthedBitsRouteChildren,
)

interface AuthedSetlistsRouteChildren {
  AuthedSetlistsIndexRoute: typeof AuthedSetlistsIndexRoute
}

const AuthedSetlistsRouteChildren: AuthedSetlistsRouteChildren = {
  AuthedSetlistsIndexRoute: AuthedSetlistsIndexRoute,
}

const AuthedSetlistsRouteWithChildren = AuthedSetlistsRoute._addFileChildren(
  AuthedSetlistsRouteChildren,
)

interface AuthedUsersRouteChildren {
  AuthedUsersIdRoute: typeof AuthedUsersIdRoute
  AuthedUsersIndexRoute: typeof AuthedUsersIndexRoute
}

const AuthedUsersRouteChildren: AuthedUsersRouteChildren = {
  AuthedUsersIdRoute: AuthedUsersIdRoute,
  AuthedUsersIndexRoute: AuthedUsersIndexRoute,
}

const AuthedUsersRouteWithChildren = AuthedUsersRoute._addFileChildren(
  AuthedUsersRouteChildren,
)

interface AuthedRouteChildren {
  AuthedBitsRoute: typeof AuthedBitsRouteWithChildren
  AuthedSetlistsRoute: typeof AuthedSetlistsRouteWithChildren
  AuthedUsersRoute: typeof AuthedUsersRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBitsRoute: AuthedBitsRouteWithChildren,
  AuthedSetlistsRoute: AuthedSetlistsRouteWithChildren,
  AuthedUsersRoute: AuthedUsersRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
