/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Variants4RouteImport } from './routes/_variants/4'
import { Route as Variants3RouteImport } from './routes/_variants/3'
import { Route as Variants2RouteImport } from './routes/_variants/2'
import { Route as Variants1RouteImport } from './routes/_variants/1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Variants4Route = Variants4RouteImport.update({
  id: '/_variants/4',
  path: '/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Variants3Route = Variants3RouteImport.update({
  id: '/_variants/3',
  path: '/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Variants2Route = Variants2RouteImport.update({
  id: '/_variants/2',
  path: '/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Variants1Route = Variants1RouteImport.update({
  id: '/_variants/1',
  path: '/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1': typeof Variants1Route
  '/2': typeof Variants2Route
  '/3': typeof Variants3Route
  '/4': typeof Variants4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1': typeof Variants1Route
  '/2': typeof Variants2Route
  '/3': typeof Variants3Route
  '/4': typeof Variants4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_variants/1': typeof Variants1Route
  '/_variants/2': typeof Variants2Route
  '/_variants/3': typeof Variants3Route
  '/_variants/4': typeof Variants4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/1' | '/2' | '/3' | '/4'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/1' | '/2' | '/3' | '/4'
  id:
    | '__root__'
    | '/'
    | '/_variants/1'
    | '/_variants/2'
    | '/_variants/3'
    | '/_variants/4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Variants1Route: typeof Variants1Route
  Variants2Route: typeof Variants2Route
  Variants3Route: typeof Variants3Route
  Variants4Route: typeof Variants4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_variants/4': {
      id: '/_variants/4'
      path: '/4'
      fullPath: '/4'
      preLoaderRoute: typeof Variants4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_variants/3': {
      id: '/_variants/3'
      path: '/3'
      fullPath: '/3'
      preLoaderRoute: typeof Variants3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_variants/2': {
      id: '/_variants/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof Variants2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_variants/1': {
      id: '/_variants/1'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof Variants1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Variants1Route: Variants1Route,
  Variants2Route: Variants2Route,
  Variants3Route: Variants3Route,
  Variants4Route: Variants4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
